### ISSUE TITLE
bug: format and content automated mails

### ISSUE THREAD

**Issue by flxmts** [BVPyro/bvpk.org#41]
Die Bestätigungsemails enthalten seltsame Umbrüche. Siehe hier: https://filebrowser.bvpk.net/share/RNsSywRf Umbrüche entfernen.

- [ ] Außerdem in allen Bestätigungsmails Text ändern auf:

Schau’ gerne auf unseren Kanälen auf Twitter und Facebook (@BVPyro) und Instagram (@bvpk_pyrotechnik) vorbei.

- [ ] Bezeichnung des Absenders bei allen Bestätigungsmail ändern zu

Bundesverband Pyrotechnik | Geschäftsstelle

(Aktuell: BVPK e.V. Geschäftsstelle)

**Comment by linozen** [comment]
Die Umbrüche sind ein notwendiges Übel. Habe nun aber trotzdem die Zeilenlänge auf 50 Zeichen gekürzt. Sollte nun besser laufen.
