### ISSUE TITLE
feat: implementation fundraising box

### ISSUE THREAD

**Issue by flxmts** [BVPyro/bvpk.org#42]
Seite anlegen, auf der folgender Code integriert wird:

Link Testseite an Andi und mich
Box optisch an die Seite anpassen

Wenn du Zugriff auf Fundraisingbox oder andere Infos brauchst, bitte Andi oder mir Bescheid kurz außerhalb von github bescheid geben.

**Comment by linozen** [comment]
Here is an implementation

https://github.com/futurice/masifunde-fe/blob/6c7ee52f6054f770443374905c21be4861071a98/README.md#fundraisingbox

**Comment by linozen** [comment]
@flxmts @andlud Den JS-Code von euch kann ich so nicht einfach auf der Webseite einbinden. Am einfachsten wäre es ihr gebt mir Zugang zum backend.

**Comment by linozen** [comment]
closed as of #
